# fly.toml app configuration file generated for aiqem-ad on 2023-07-17T12:34:23+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "aiqem-ad"
primary_region = "ams"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
